import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router';
import { classAssessmentApi } from '@/features/assessments/api';
import type { GradingDetail } from '@/features/assessments/types';
import { useSessionExpiry } from '@/features/auth/use-session-expiry';

type Scores = Record<string, Record<string, string>>;
type Feedback = Record<string, string>;
export function AssessmentGradingDetailPage() {
  const { classOfferingId, classAssessmentId, attemptId } = useParams<{ classOfferingId: string; classAssessmentId: string; attemptId: string }>();
  const redirectExpiredSession = useSessionExpiry();
  const [detail, setDetail] = useState<GradingDetail | null>(null);
  const [scores, setScores] = useState<Scores>({});
  const [feedback, setFeedback] = useState<Feedback>({});
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); if (!classOfferingId || !classAssessmentId || !attemptId) return; void classAssessmentApi.gradingDetail(classOfferingId, classAssessmentId, attemptId, controller.signal).then((data) => { setDetail(data); setScores(initialScores(data)); setFeedback(initialFeedback(data)); }).catch(async (requestError) => { if (requestError instanceof Error && requestError.name === 'AbortError') return; if (await redirectExpiredSession(requestError)) return; setError('Không thể tải bài làm để chấm.'); }); return () => controller.abort(); }, [attemptId, classAssessmentId, classOfferingId, redirectExpiredSession]);
  const save = async (answer: GradingDetail['answers'][number], finalize: boolean) => { if (!classOfferingId || !classAssessmentId || !attemptId) return; const rubric = answer.testQuestion.question.rubric; const values = scores[answer.testQuestion.id] ?? {}; if (rubric.criteria.some((criterion) => values[criterion.id] === '' || values[criterion.id] === undefined)) { setError('Vui lòng nhập điểm cho tất cả tiêu chí.'); return; } setSaving(answer.testQuestion.id); setError(null); try { await classAssessmentApi.gradeAnswer(classOfferingId, classAssessmentId, attemptId, answer.testQuestion.id, { criteria: rubric.criteria.map((criterion) => ({ rubricCriterionId: criterion.id, score: values[criterion.id] })), feedback: feedback[answer.testQuestion.id] ?? '', finalize, editFinal: answer.evaluation?.status === 'REVIEWED_FINAL' }); const data = await classAssessmentApi.gradingDetail(classOfferingId, classAssessmentId, attemptId); setDetail(data); setScores(initialScores(data)); setFeedback(initialFeedback(data)); } catch { setError('Không thể lưu kết quả chấm. Kiểm tra điểm theo giới hạn từng tiêu chí.'); } finally { setSaving(null); } };
  if (!detail) return <p className="p-8 text-center text-slate-500">Đang tải bài làm...</p>;
  return <main className="mx-auto max-w-5xl space-y-6 px-4 py-8"><div><Link className="text-sm text-blue-700 hover:underline" to={`/instructor/classes/${classOfferingId}/assessments/${classAssessmentId}/grading`}>← Danh sách chấm bài</Link><h1 className="mt-3 text-2xl font-bold">Bài làm của {detail.learner.fullName}</h1><p className="text-sm text-slate-600">{detail.test.title} · {detail.learner.email} · lượt {detail.attemptNumber}</p></div>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-red-700" role="alert">{error}</div>}{detail.answers.map((answer) => { const rubric = answer.testQuestion.question.rubric; const isFinal = answer.evaluation?.status === 'REVIEWED_FINAL'; return <article className="rounded-2xl border bg-white p-6 shadow-sm" key={answer.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase text-indigo-700">{answer.testQuestion.question.toeicSkill}</p><h2 className="mt-2 whitespace-pre-wrap text-lg font-semibold">{answer.testQuestion.question.content}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${isFinal ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'}`}>{isFinal ? 'Đã chấm cuối' : 'Chờ chấm'}</span></div>{answer.textResponse && <div className="mt-4 whitespace-pre-wrap rounded-lg bg-slate-50 p-4">{answer.textResponse}</div>}{answer.audioUrl && <audio className="mt-4 w-full" controls src={answer.audioUrl} />}
      <div className="mt-5"><h3 className="font-bold">{rubric.name}</h3><div className="mt-3 space-y-3">{rubric.criteria.map((criterion) => <label className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[1fr_8rem]" key={criterion.id}><span><span className="font-medium">{criterion.name}</span>{criterion.description && <span className="mt-1 block text-xs text-slate-500">{criterion.description}</span>}<span className="mt-1 block text-xs text-slate-500">Trọng số {criterion.weight}</span></span><span className="flex items-center gap-2"><input className="w-full rounded border p-2" min="0" max={criterion.maxScore} step="0.01" type="number" value={scores[answer.testQuestion.id]?.[criterion.id] ?? ''} onChange={(event) => setScores((current) => ({ ...current, [answer.testQuestion.id]: { ...current[answer.testQuestion.id], [criterion.id]: event.target.value } }))}/><span className="text-sm">/{criterion.maxScore}</span></span></label>)}</div></div><label className="mt-4 block text-sm font-medium">Nhận xét<textarea className="mt-1 min-h-24 w-full rounded border p-3" value={feedback[answer.testQuestion.id] ?? ''} onChange={(event) => setFeedback((current) => ({ ...current, [answer.testQuestion.id]: event.target.value }))}/></label><div className="mt-4 flex justify-end gap-2"><button className="rounded border px-4 py-2 text-sm" disabled={saving !== null} onClick={() => void save(answer, false)}>Lưu nháp</button><button className="rounded bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={saving !== null} onClick={() => void save(answer, true)}>{saving === answer.testQuestion.id ? 'Đang lưu...' : isFinal ? 'Cập nhật điểm cuối' : 'Xác nhận điểm cuối'}</button></div></article>; })}</main>;
}
function initialScores(data: GradingDetail): Scores { return Object.fromEntries(data.answers.map((answer) => [answer.testQuestion.id, Object.fromEntries(answer.testQuestion.question.rubric.criteria.map((criterion) => [criterion.id, String(answer.evaluation?.criterionScores.find((score) => score.rubricCriterionId === criterion.id)?.score ?? '')]))])); }
function initialFeedback(data: GradingDetail): Feedback { return Object.fromEntries(data.answers.map((answer) => [answer.testQuestion.id, answer.evaluation?.feedback ?? ''])); }
