import { FormEvent, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router';
import { classAssessmentApi } from '@/features/assessments/api';
import type { AssessmentStage, ClassAssessmentWorkspace } from '@/features/assessments/types';
import { useSessionExpiry } from '@/features/auth/use-session-expiry';

const stageLabels: Record<AssessmentStage, string> = { PERIODIC: 'Thường kỳ', MIDTERM: 'Giữa kỳ', FINAL: 'Cuối kỳ' };
export function ClassAssessmentManagementPage() {
  const { classOfferingId } = useParams<{ classOfferingId: string }>();
  const redirectExpiredSession = useSessionExpiry();
  const [workspace, setWorkspace] = useState<ClassAssessmentWorkspace | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [version, setVersion] = useState(0);
  const [form, setForm] = useState({ testId: '', stage: 'PERIODIC' as AssessmentStage, openAt: '', closeAt: '', maxAttempts: '1' });
  useEffect(() => { const controller = new AbortController(); if (!classOfferingId) return; void classAssessmentApi.list(classOfferingId, controller.signal).then((data) => { setWorkspace(data); setForm((current) => ({ ...current, testId: current.testId || data.availableTests[0]?.id || '' })); }).catch(async (requestError) => { if (requestError instanceof Error && requestError.name === 'AbortError') return; if (await redirectExpiredSession(requestError)) return; setError('Không thể tải lịch bài kiểm tra của lớp.'); }); return () => controller.abort(); }, [classOfferingId, redirectExpiredSession, version]);
  const create = async (event: FormEvent) => { event.preventDefault(); if (!classOfferingId || !form.testId) return; setBusy(true); setError(null); try { await classAssessmentApi.create(classOfferingId, { testId: form.testId, stage: form.stage, openAt: form.openAt ? new Date(form.openAt).toISOString() : null, closeAt: form.closeAt ? new Date(form.closeAt).toISOString() : null, maxAttemptsOverride: Number(form.maxAttempts), isActive: true }); setVersion((value) => value + 1); } catch { setError('Không thể giao bài. Hãy kiểm tra thời gian mở/đóng và bài kiểm tra đã chọn.'); } finally { setBusy(false); } };
  const toggleActive = async (id: string, isActive: boolean) => { if (!classOfferingId) return; setBusy(true); try { await classAssessmentApi.update(classOfferingId, id, { isActive: !isActive }); setVersion((value) => value + 1); } catch { setError('Không thể cập nhật trạng thái bài kiểm tra.'); } finally { setBusy(false); } };
  if (!workspace) return <p className="p-8 text-center text-slate-500">Đang tải lịch bài kiểm tra...</p>;
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-8"><div><Link className="text-sm font-medium text-blue-700 hover:underline" to="/instructor/teaching">← Lớp giảng dạy</Link><h1 className="mt-3 text-2xl font-bold">Bài kiểm tra · {workspace.classOffering.name}</h1><p className="text-sm text-slate-600">{workspace.classOffering.code} · {workspace.classOffering.course.title}</p></div>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-red-700" role="alert">{error}</div>}
    <form className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-2" onSubmit={(event) => void create(event)}><h2 className="text-lg font-bold md:col-span-2">Giao bài kiểm tra</h2><label className="text-sm font-medium">Bài kiểm tra<select className="mt-1 w-full rounded border p-2" value={form.testId} onChange={(e) => setForm({ ...form, testId: e.target.value })}>{workspace.availableTests.map((test) => <option key={test.id} value={test.id}>{test.title} · {test.timeLimitMinutes ?? '—'} phút</option>)}</select></label><label className="text-sm font-medium">Loại đánh giá<select className="mt-1 w-full rounded border p-2" value={form.stage} onChange={(e) => setForm({ ...form, stage: e.target.value as AssessmentStage })}>{Object.entries(stageLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-medium">Mở từ<input className="mt-1 w-full rounded border p-2" type="datetime-local" value={form.openAt} onChange={(e) => setForm({ ...form, openAt: e.target.value })}/></label><label className="text-sm font-medium">Đóng lúc<input className="mt-1 w-full rounded border p-2" type="datetime-local" value={form.closeAt} onChange={(e) => setForm({ ...form, closeAt: e.target.value })}/></label><label className="text-sm font-medium">Số lượt tối đa<input className="mt-1 w-full rounded border p-2" min="1" type="number" value={form.maxAttempts} onChange={(e) => setForm({ ...form, maxAttempts: e.target.value })}/></label><div className="flex items-end"><button className="rounded bg-blue-600 px-5 py-2 font-semibold text-white disabled:opacity-50" disabled={busy || !form.testId}>{busy ? 'Đang lưu...' : 'Giao bài'}</button></div></form>
    <section><h2 className="mb-3 text-lg font-bold">Lịch đã giao</h2>{workspace.assessments.length === 0 ? <div className="rounded-xl border bg-white p-8 text-center text-slate-500">Lớp chưa có bài kiểm tra.</div> : <div className="grid gap-4 md:grid-cols-2">{workspace.assessments.map((assessment) => <article className="rounded-xl border bg-white p-5 shadow-sm" key={assessment.id}><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-indigo-100 px-2.5 py-1 text-xs font-bold text-indigo-800">{stageLabels[assessment.stage]}</span><h3 className="mt-2 font-bold">{assessment.test.title}</h3></div><span className={`text-xs font-semibold ${assessment.isActive ? 'text-emerald-700' : 'text-slate-500'}`}>{assessment.isActive ? 'Đang hoạt động' : 'Đã tắt'}</span></div><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-slate-500">Bài đã nộp</dt><dd className="font-semibold">{assessment.submissionCount}</dd></div><div><dt className="text-slate-500">Chờ chấm</dt><dd className="font-semibold text-amber-700">{assessment.pendingGradingCount}</dd></div></dl><p className="mt-3 text-xs text-slate-500">{formatWindow(assessment.openAt, assessment.closeAt)}</p><div className="mt-4 flex gap-2"><Link className="rounded bg-indigo-600 px-3 py-2 text-sm font-medium text-white" to={`/instructor/classes/${classOfferingId}/assessments/${assessment.id}/grading`}>Chấm bài</Link><button className="rounded border px-3 py-2 text-sm" disabled={busy} onClick={() => void toggleActive(assessment.id, assessment.isActive)}>{assessment.isActive ? 'Tắt bài' : 'Bật lại'}</button></div></article>)}</div>}</section>
  </main>;
}
function formatWindow(openAt: string | null, closeAt: string | null) { return `${openAt ? new Date(openAt).toLocaleString('vi-VN') : 'Mở ngay'} → ${closeAt ? new Date(closeAt).toLocaleString('vi-VN') : 'Không giới hạn'}`; }
