import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router';
import { instructorApi } from '@/features/instructor/api';
import type { InstructorLearnerDetail } from '@/features/instructor/types';

export function InstructorLearnerDetailPage() {
  const { classOfferingId = '', enrollmentId = '' } = useParams();
  const [data, setData] = useState<InstructorLearnerDetail | null>(null); const [error, setError] = useState(false);
  useEffect(() => { const c = new AbortController(); void instructorApi.classes.learner(classOfferingId, enrollmentId, c.signal).then((loaded) => { setData(loaded); setError(false); }).catch((cause: unknown) => { if (!(cause instanceof Error && cause.name === 'AbortError')) setError(true); }); return () => c.abort(); }, [classOfferingId, enrollmentId]);
  if (error) return <div className="state-error">Không thể tải hồ sơ học viên hoặc bạn không có quyền truy cập.</div>; if (!data) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />;
  const raw = data;
  return <div className="space-y-6"><section className="rounded-2xl border bg-white p-6"><Link className="text-sm font-semibold text-indigo-700" to={`/instructor/classes/${classOfferingId}/learners`}>← Danh sách học viên</Link><h2 className="mt-3 text-2xl font-bold">{raw.enrollment.learner.fullName}</h2><p className="text-slate-500">{raw.enrollment.learner.email}</p></section><section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Ảnh chụp bốn kỹ năng gần nhất</h3>{raw.latestFourSkillSnapshot ? <div className="mt-4"><p className="text-sm text-slate-500">{raw.latestFourSkillSnapshot.assessmentTitle} · cùng một bài kiểm tra đã chấm hoàn tất</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{raw.latestFourSkillSnapshot.scores.map((score) => <div className="rounded-xl bg-indigo-50 p-3" key={score.skill}><strong>{score.skill}</strong><p className="text-xl font-bold text-indigo-700">{score.normalizedScore}%</p></div>)}</div></div> : <p className="mt-3 text-slate-500">Chưa có bài kiểm tra trong lớp được chấm hoàn tất đủ bốn kỹ năng.</p>}</section><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Tiến độ bài học</h3><div className="mt-3 space-y-2">{raw.lessonProgress.map((p) => <div className="flex justify-between rounded-lg bg-slate-50 p-3" key={p.lesson.id}><span><small className="block text-slate-500">{p.lesson.module.title}</small>{p.lesson.title}</span><strong className={p.status === 'COMPLETED' ? 'text-emerald-700' : 'text-slate-500'}>{p.status === 'COMPLETED' ? 'Hoàn thành' : p.status === 'IN_PROGRESS' ? 'Đang học' : 'Chưa bắt đầu'}</strong></div>)}</div></div><div className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Lịch sử bài kiểm tra</h3><div className="mt-3 space-y-3">{raw.attempts.map((a) => <article className="rounded-lg bg-slate-50 p-3" key={a.id}><div className="flex justify-between"><strong>{a.classAssessment?.test.title ?? 'Bài kiểm tra'}</strong><span className="text-sm">Lượt {a.attemptNumber}</span></div><div className="mt-2 flex flex-wrap gap-2">{a.skillScores.map((s) => <span className="rounded-full border px-2 py-1 text-xs" key={s.skill}>{s.skill}: {s.status === 'FINAL' ? `${s.normalizedScore}%` : 'Đang chờ'}</span>)}</div>{a.feedback?.filter((f) => f.feedback).map((f, i) => <p className="mt-2 text-sm text-slate-600" key={i}>Nhận xét: {f.feedback}</p>)}</article>)}{raw.attempts.length === 0 ? <p className="text-slate-500">Chưa có bài đã nộp.</p> : null}</div></div></section></div>;
}
