import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router';
import { toeicSkillLabel } from '@/features/assessments/display';
import type { ToeicSkill } from '@/features/assessments/types';
import { instructorApi } from '@/features/instructor/api';

const skills: ToeicSkill[] = ['LISTENING', 'READING', 'SPEAKING', 'WRITING'];
type SkillScore = { skill: ToeicSkill; status: string; normalizedScore: number };
type AssessmentResult = { id: string; stage: string; test: { title: string }; submittedCount: number; latestAttemptCount: number; fullyGradedCount: number; pendingGradingCount: number; skillAverages: Array<{ skill: ToeicSkill; average: number | null; sampleCount: number; excludedCount: number }>; learners: Array<{ id: string; learner: { fullName: string; email: string }; attemptNumber: number; label: string; skillScores: SkillScore[] }> };
function scoreLabel(scores: SkillScore[], skill: ToeicSkill) { const score = scores.find((item) => item.skill === skill); return score?.status === 'FINAL' ? `${score.normalizedScore}%` : score ? 'Đang chờ' : 'Chưa có'; }

export function InstructorClassResultsPage() {
  const { classOfferingId = '' } = useParams();
  const [assessments, setAssessments] = useState<AssessmentResult[]>([]); const [selected, setSelected] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { const controller = new AbortController(); void instructorApi.classes.results(classOfferingId, controller.signal).then((data) => { const rows = data.assessments as AssessmentResult[]; setAssessments(rows); setSelected(rows[0]?.id ?? ''); setError(false); }).catch((cause: unknown) => { if (!(cause instanceof Error && cause.name === 'AbortError')) setError(true); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [classOfferingId]);
  const assessment = useMemo(() => assessments.find((item) => item.id === selected), [assessments, selected]);
  const gradingUrl = (id: string) => `/instructor/classes/${classOfferingId}/assessments/${assessment?.id}/attempts/${id}/grading`;
  if (error) return <div className="state-error">Không thể tải kết quả lớp.</div>; if (loading) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />;
  return <div className="space-y-5"><section className="rounded-2xl border bg-white p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold">Kết quả lớp</h2><p className="text-sm text-slate-500">Điểm trung bình chỉ tính các kỹ năng đã chốt; trạng thái chờ hoặc thiếu được loại khỏi mẫu.</p></div><select aria-label="Chọn bài kiểm tra" className="rounded-lg border px-3 py-2" onChange={(event) => setSelected(event.target.value)} value={selected}>{assessments.map((item) => <option key={item.id} value={item.id}>{item.test.title}</option>)}</select></div></section>{assessment ? <>
    <section className="grid gap-3 sm:grid-cols-3"><Metric label="Lượt đã nộp" value={assessment.submittedCount} /><Metric label="Đã chấm đủ" value={assessment.fullyGradedCount} /><Metric label="Đang chờ chấm" value={assessment.pendingGradingCount} /></section>
    <section className="rounded-2xl border bg-white p-5"><div className="flex justify-between text-sm"><strong>Tiến độ hoàn tất chấm</strong><span>{assessment.latestAttemptCount ? Math.round(assessment.fullyGradedCount / assessment.latestAttemptCount * 100) : 0}%</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${assessment.latestAttemptCount ? assessment.fullyGradedCount / assessment.latestAttemptCount * 100 : 0}%` }} /></div><p className="mt-2 text-xs text-slate-500">Tính trên {assessment.latestAttemptCount} lượt gần nhất của từng học viên.</p></section>
    <section className="grid gap-3 sm:grid-cols-4">{assessment.skillAverages.map((item) => <div className="rounded-xl border bg-white p-4" key={item.skill}><strong>{toeicSkillLabel[item.skill]}</strong><p className="mt-2 text-2xl font-bold text-indigo-700">{item.average === null ? '—' : `${item.average}%`}</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-indigo-600" style={{ width: `${item.average ?? 0}%` }} /></div><p className="mt-2 text-xs text-slate-500">Mẫu {item.sampleCount} · loại trừ {item.excludedCount}</p></div>)}</section>
    <section className="hidden overflow-hidden rounded-2xl border bg-white md:block"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr className="border-b text-left"><th className="p-3">Học viên</th><th className="p-3">Lượt</th>{skills.map((skill) => <th className="p-3" key={skill}>{toeicSkillLabel[skill]}</th>)}<th className="p-3">Chi tiết</th></tr></thead><tbody>{assessment.learners.map((attempt, index) => <tr className={index % 2 ? 'bg-slate-50/70' : ''} key={attempt.id}><td className="p-3"><strong>{attempt.learner.fullName}</strong><br/><span className="text-slate-500">{attempt.learner.email}</span></td><td className="p-3">{attempt.label} · #{attempt.attemptNumber}</td>{skills.map((skill) => <td className="p-3" key={skill}>{scoreLabel(attempt.skillScores, skill)}</td>)}<td className="p-3"><Link className="font-semibold text-indigo-700" to={gradingUrl(attempt.id)}>Xem</Link></td></tr>)}</tbody></table></section>
    <section className="grid gap-3 md:hidden" data-testid="mobile-results-cards">{assessment.learners.map((attempt) => <article className="rounded-xl border bg-white p-4" key={attempt.id}><h3 className="font-semibold">{attempt.learner.fullName}</h3><p className="break-all text-sm text-slate-500">{attempt.learner.email}</p><p className="mt-2 text-sm">{attempt.label} · Lượt #{attempt.attemptNumber}</p><dl className="mt-3 grid grid-cols-2 gap-2">{skills.map((skill) => <div className="rounded-lg bg-slate-50 p-2" key={skill}><dt className="text-xs text-slate-500">{toeicSkillLabel[skill]}</dt><dd className="font-semibold">{scoreLabel(attempt.skillScores, skill)}</dd></div>)}</dl><Link className="mt-4 inline-block font-semibold text-indigo-700" to={gradingUrl(attempt.id)}>Xem chi tiết</Link></article>)}</section>
  </> : <div className="rounded-2xl border bg-white p-10 text-center text-slate-500">Chưa có bài kiểm tra trong lớp.</div>}</div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold text-indigo-700">{value}</p></div>; }
