import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router';
import { instructorApi } from '@/features/instructor/api';
import type { InstructorGradingInbox } from '@/features/instructor/types';

const labels: Record<string, string> = { WAITING: 'Chờ chấm', PARTIAL: 'Đang chấm dở', FINAL: 'Đã chấm' };
export function InstructorClassGradingPage() {
  const { classOfferingId = '' } = useParams(); const [data, setData] = useState<InstructorGradingInbox | null>(null); const [filter, setFilter] = useState('ALL'); const [search, setSearch] = useState(''); const [error, setError] = useState(false);
  useEffect(() => { const c = new AbortController(); void instructorApi.classes.grading(classOfferingId, c.signal).then((loaded) => { setData(loaded); setError(false); }).catch((cause: unknown) => { if (!(cause instanceof Error && cause.name === 'AbortError')) setError(true); }); return () => c.abort(); }, [classOfferingId]);
  const rows = useMemo(() => data?.submissions.filter((s) => (filter === 'ALL' || s.gradingState === filter) && `${s.learner.fullName} ${s.classAssessment.test.title}`.toLowerCase().includes(search.toLowerCase())) ?? [], [data, filter, search]);
  if (error) return <div className="state-error">Không thể tải danh sách chấm bài.</div>; if (!data) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />;
  return <section className="rounded-2xl border bg-white p-5"><h2 className="text-2xl font-bold">Chấm bài</h2><p className="mt-1 text-sm text-slate-500">Ưu tiên bài nộp sớm nhất. Bộ lọc không thay đổi dữ liệu bài làm.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select aria-label="Lọc trạng thái chấm" className="rounded-lg border px-3 py-2" onChange={(e) => setFilter(e.target.value)} value={filter}><option value="ALL">Tất cả trạng thái</option><option value="WAITING">Chờ chấm</option><option value="PARTIAL">Đang chấm dở</option><option value="FINAL">Đã chấm</option></select><input aria-label="Tìm học viên hoặc bài kiểm tra" className="rounded-lg border px-3 py-2" onChange={(e) => setSearch(e.target.value)} placeholder="Tìm học viên hoặc bài kiểm tra" /></div><div className="mt-5 space-y-3">{rows.map((s) => <article className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center" key={s.id}><div><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-bold text-indigo-700">{labels[s.gradingState] ?? s.gradingState}</span><h3 className="mt-2 font-bold">{s.learner.fullName}</h3><p className="text-sm text-slate-500">{s.classAssessment.test.title} · lượt {s.attemptNumber} · {s.submittedAt ? new Date(s.submittedAt).toLocaleString('vi-VN') : ''}</p></div><Link className="rounded-lg bg-indigo-600 px-4 py-2 text-center font-semibold text-white" to={`/instructor/classes/${classOfferingId}/assessments/${s.classAssessment.id}/attempts/${s.id}/grading`}>{s.gradingState === 'WAITING' ? 'Chấm bài' : s.gradingState === 'PARTIAL' ? 'Tiếp tục chấm' : 'Xem / chỉnh điểm'}</Link></article>)}{rows.length === 0 ? <p className="py-8 text-center text-slate-500">Không có bài phù hợp.</p> : null}</div></section>;
}
