import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router';
import { instructorApi } from '@/features/instructor/api';

type AssessmentResult = { id: string; stage: string; test: { title: string }; submittedCount: number; latestAttemptCount: number; fullyGradedCount: number; pendingGradingCount: number; skillAverages: Array<{ skill: string; average: number | null; sampleCount: number; excludedCount: number }>; learners: Array<{ id: string; learner: { fullName: string; email: string }; attemptNumber: number; label: string; skillScores: Array<{ skill: string; status: string; normalizedScore: number }> }> };
export function InstructorClassResultsPage() {
  const { classOfferingId = '' } = useParams(); const [assessments, setAssessments] = useState<AssessmentResult[]>([]); const [selected, setSelected] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { const c = new AbortController(); void instructorApi.classes.results(classOfferingId, c.signal).then((data) => { const rows = data.assessments as AssessmentResult[]; setAssessments(rows); setSelected(rows[0]?.id ?? ''); setError(false); }).catch((cause: unknown) => { if (!(cause instanceof Error && cause.name === 'AbortError')) setError(true); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [classOfferingId]);
  const assessment = useMemo(() => assessments.find((a) => a.id === selected), [assessments, selected]);
  if (error) return <div className="state-error">Không thể tải kết quả lớp.</div>; if (loading) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />;
  return <div className="space-y-5"><section className="rounded-2xl border bg-white p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold">Kết quả lớp</h2><p className="text-sm text-slate-500">Điểm trung bình chỉ dùng AttemptSkillScore đã chốt; trạng thái chờ hoặc thiếu được loại khỏi mẫu.</p></div><select aria-label="Chọn bài kiểm tra" className="rounded-lg border px-3 py-2" onChange={(e) => setSelected(e.target.value)} value={selected}>{assessments.map((a) => <option key={a.id} value={a.id}>{a.test.title}</option>)}</select></div></section>{assessment ? <><section className="rounded-xl border bg-white p-4 text-sm"><strong>{assessment.submittedCount}</strong> lượt đã nộp · <strong>{assessment.fullyGradedCount}</strong> học viên đã chấm đủ · <strong>{assessment.pendingGradingCount}</strong> học viên đang chờ chấm <span className="text-slate-500">(đang hiển thị {assessment.latestAttemptCount} lượt gần nhất)</span></section><section className="grid gap-3 sm:grid-cols-4">{assessment.skillAverages.map((s) => <div className="rounded-xl border bg-white p-4" key={s.skill}><strong>{s.skill}</strong><p className="mt-2 text-2xl font-bold text-indigo-700">{s.average === null ? '—' : `${s.average}%`}</p><p className="text-xs text-slate-500">Mẫu {s.sampleCount} · loại trừ {s.excludedCount}</p></div>)}</section><section className="overflow-x-auto rounded-2xl border bg-white p-5"><table className="min-w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Học viên</th><th className="p-3">Lượt</th>{['LISTENING','READING','SPEAKING','WRITING'].map((s) => <th className="p-3" key={s}>{s[0]}</th>)}<th className="p-3">Chi tiết</th></tr></thead><tbody>{assessment.learners.map((a) => <tr className="border-b" key={a.id}><td className="p-3"><strong>{a.learner.fullName}</strong><br/><span className="text-slate-500">{a.learner.email}</span></td><td className="p-3">{a.label} · #{a.attemptNumber}</td>{['LISTENING','READING','SPEAKING','WRITING'].map((skill) => { const score = a.skillScores.find((s) => s.skill === skill); return <td className="p-3" key={skill}>{score?.status === 'FINAL' ? `${score.normalizedScore}%` : score ? 'Đang chờ' : 'Thiếu'}</td>; })}<td className="p-3"><Link className="font-semibold text-indigo-700" to={`/instructor/classes/${classOfferingId}/assessments/${assessment.id}/attempts/${a.id}/grading`}>Xem</Link></td></tr>)}</tbody></table></section></> : <div className="rounded-2xl border bg-white p-10 text-center text-slate-500">Chưa có bài kiểm tra trong lớp.</div>}</div>;
}
