import { Link, useOutletContext } from 'react-router';
import type { InstructorClassWorkspaceContext } from '@/layouts/InstructorClassWorkspaceLayout';

export function InstructorClassOverviewPage() {
  const { overview } = useOutletContext<InstructorClassWorkspaceContext>();
  const base = `/instructor/classes/${overview.classOffering.id}`;
  return <div className="space-y-6"><section className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-wider text-indigo-600">Không gian giảng dạy</p><h2 className="mt-2 text-3xl font-bold">Tổng quan lớp</h2><p className="mt-2 text-slate-600">Theo dõi tiến độ, lịch bài kiểm tra và công việc chấm bài của lớp.</p></section><section className="grid gap-4 sm:grid-cols-3"><Metric label="Học viên đang học" value={overview.activeLearnerCount} /><Metric label="Tiến độ bài học" value={`${overview.lessonProgress.percentage}%`} detail={`${overview.lessonProgress.completed}/${overview.lessonProgress.total} lượt hoàn thành`} /><Metric label="Bài chờ chấm" value={overview.pendingGradingCount} /></section><section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">Lịch bài kiểm tra</h3><p className="text-sm text-slate-500">Mốc mở, đóng và tỷ lệ học viên đã nộp.</p></div><Link className="text-sm font-semibold text-indigo-700" to={`${base}/assessments`}>Quản lý lịch →</Link></div>{overview.assessments.length ? <div className="mt-4 overflow-hidden rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">Bài kiểm tra</th><th className="p-3">Thời gian</th><th className="p-3">Đã nộp</th><th className="p-3">Trạng thái</th></tr></thead><tbody className="divide-y">{overview.assessments.map((a) => <tr key={a.id}><td className="p-3 font-semibold">{a.test.title}</td><td className="p-3 text-slate-600">{formatDate(a.openAt)} – {formatDate(a.closeAt)}</td><td className="p-3"><strong>{a.submittedLearnerCount}</strong>/{a.activeLearnerCount} học viên</td><td className="p-3"><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-semibold text-indigo-700">{a.availability === 'OPEN' ? 'Đang mở' : a.availability === 'UPCOMING' ? 'Sắp mở' : 'Đã đóng'}</span></td></tr>)}</tbody></table></div> : <p className="mt-4 text-slate-500">Chưa có lịch bài kiểm tra.</p>}</section></div>;
}
function Metric({ label, value, detail }: { label: string; value: string | number; detail?: string }) { return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-indigo-700">{value}</p>{detail ? <p className="mt-1 text-xs text-slate-500">{detail}</p> : null}</div>; }
function formatDate(value: string | null): string { return value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : 'Không giới hạn'; }
