import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router';
import { instructorApi } from '@/features/instructor/api';
import type { InstructorRoster } from '@/features/instructor/types';

export function InstructorRosterPage() {
  const { classOfferingId = '' } = useParams();
  const [data, setData] = useState<InstructorRoster | null>(null); const [error, setError] = useState(false); const [search, setSearch] = useState('');
  useEffect(() => { const c = new AbortController(); void instructorApi.classes.learners(classOfferingId, c.signal).then((loaded) => { setData(loaded); setError(false); }).catch((cause: unknown) => { if (!(cause instanceof Error && cause.name === 'AbortError')) setError(true); }); return () => c.abort(); }, [classOfferingId]);
  const rows = useMemo(() => data?.learners.filter((item) => `${item.learner.fullName} ${item.learner.email}`.toLowerCase().includes(search.toLowerCase())) ?? [], [data, search]);
  if (error) return <div className="state-error">Không thể tải danh sách học viên.</div>; if (!data) return <div className="h-56 animate-pulse rounded-2xl bg-slate-200" role="status" />;
  return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold">Học viên</h2><p className="text-sm text-slate-500">Chỉ xem tiến độ; thành viên lớp được quản lý bởi điều phối viên.</p></div><input aria-label="Tìm học viên" className="rounded-xl border px-3 py-2" onChange={(e) => setSearch(e.target.value)} placeholder="Tìm tên hoặc email" value={search} /></div><div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Học viên</th><th className="p-3">Trạng thái</th><th className="p-3">Bài học</th><th className="p-3">Bài đã nộp</th><th className="p-3">Chờ chấm</th><th className="p-3"></th></tr></thead><tbody>{rows.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="p-3"><strong>{item.learner.fullName}</strong><br/><span className="text-slate-500">{item.learner.email}</span></td><td className="p-3">{item.status === 'ACTIVE' ? 'Đang học' : item.status}</td><td className="p-3">{item.completedLessons}/{item.totalLessons} · {item.progressPercentage}%</td><td className="p-3">{item.submittedAssessmentCount}</td><td className="p-3">{item.pendingGradingCount}</td><td className="p-3"><Link className="font-semibold text-indigo-700" to={`/instructor/classes/${classOfferingId}/learners/${item.id}`}>Xem chi tiết</Link></td></tr>)}</tbody></table>{rows.length === 0 ? <p className="py-8 text-center text-slate-500">Không có học viên phù hợp.</p> : null}</div></section>;
}
