import { Link, useOutletContext } from 'react-router';
import type { InstructorClassWorkspaceContext } from '@/layouts/InstructorClassWorkspaceLayout';

export function InstructorClassOverviewPage() {
  const { overview } = useOutletContext<InstructorClassWorkspaceContext>();
  const base = `/instructor/classes/${overview.classOffering.id}`;
  return <div className="space-y-6"><section className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-wider text-indigo-600">Không gian giảng dạy</p><h2 className="mt-2 text-3xl font-bold">Tổng quan lớp</h2><p className="mt-2 text-slate-600">Theo dõi tiến độ, lịch bài kiểm tra và công việc chấm bài của lớp.</p></section><section className="grid gap-4 sm:grid-cols-3"><Metric label="Học viên đang học" value={overview.activeLearnerCount} /><Metric label="Tiến độ bài học" value={`${overview.lessonProgress.percentage}%`} /><Metric label="Bài chờ chấm" value={overview.pendingGradingCount} /></section><section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">Bài kiểm tra sắp tới / đang mở</h3><Link className="text-sm font-semibold text-indigo-700" to={`${base}/assessments`}>Quản lý lịch →</Link></div>{overview.assessments.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{overview.assessments.map((a) => <article className="rounded-xl bg-slate-50 p-4" key={a.id}><strong>{a.test.title}</strong><p className="mt-1 text-sm text-slate-500">{a.availability === 'OPEN' ? 'Đang mở' : a.availability === 'UPCOMING' ? 'Sắp mở' : 'Đã đóng'}</p></article>)}</div> : <p className="mt-4 text-slate-500">Chưa có lịch bài kiểm tra.</p>}</section></div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-indigo-700">{value}</p></div>; }
